### ISSUE TITLE
Is it tested on the ATSAMD21J18A

### ISSUE THREAD

**Issue by rs-development** [opendime/DAFU#2]
Did you test with an ATSAMD21J18A? Windows seems to be not able to recognise the USB device. Is there any need for external Crystals or similar?

**Comment by doc-hex** [comment]
Have not tested ATSAMD21J18A. Crystals should not be needed.

**Comment by rs-development** [comment]
I will report if i can fix it.

**Comment by rs-development** [comment]
I did not look deeper into it but instead used this bootloader which works fine for the D21J18A.

https://github.com/microsoft/uf2-samdx1
